SipmleCRUD/Controllers/AddEemployeeController.cs
using SipmleCRUD.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SipmleCRUD.Controllers
{
    public class AddEemployeeController : Controller
    {     //Employee db = new Employee
          // GET: AddEemployee
        TestEntities2 db = new TestEntities2();
        public ActionResult AddEmployeeInfo()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddEmployeeInfo(Employee model)
        {
            Employee emp = new Employee();
            emp.EmployeeID = model.EmployeeID;
            emp.Name = model.Name;
            emp.Father_Name = model.Father_Name;
            emp.Mother_Name = model.Mother_Name;
            emp.NID = model.NID;
            emp.Present_Address = model.Present_Address;
            emp.Permanent_Address = model.Permanent_Address;
            emp.Join_Date = model.Join_Date;
            emp.Designation = model.Designation;
            emp.Basic = model.Basic;
            emp.Bank_A_C_No = model.Bank_A_C_No;
            db.Employees.Add(emp);
            db.SaveChanges();  
            return View("AllEmployeeDetails");
        }

        public ActionResult AllEmployeeDetails()
        {
            var item = db.Employees.ToList();
            return View(item);
        }
        public ActionResult Delete(int id)
        {
            var item = db.Employees.Where(x => x.ID == id).First();
            db.Employees.Remove(item);
            db.SaveChanges();
            var item2 = db.Employees.ToList();
            return View("AllEmployeeDetails", item2);
        }
        public ActionResult EditEmployee(int id)
        {
            var item = db.Employees.Where(x => x.ID == id).First();
            return View(item);
        }

        [HttpPost]
        public ActionResult EditEmployee(Employee model)
        {
            var item = db.Employees.Where(x => x.ID == model.ID).First();
            item.EmployeeID = model.EmployeeID;
            item.Name = model.Name;
            item.Father_Name = model.Father_Name;
            item.Mother_Name = model.Mother_Name;
            item.NID = model.NID;
            item.Present_Address = model.Present_Address;
            item.Permanent_Address = model.Permanent_Address;
            item.Join_Date = model.Join_Date;
            item.Designation = model.Designation;
            item.Basic = model.Basic;
            item.Bank_A_C_No = model.Bank_A_C_No;
            db.SaveChanges();
            var item2 = db.Employees.ToList();
            return View("AllEmployeeDetails", item2);
        }
    }
}

SipmleCRUD/Controllers/RegisterController.cs
using SipmleCRUD.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SipmleCRUD.Controllers
{
    public class RegisterController : Controller
    {
        TestEntities1 db = new TestEntities1();
        // GET: Register
        public ActionResult SetDataInDataBase()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SetDataInDataBase(tblUser model)
        {
            tblUser tbl = new tblUser();
            tbl.Name = model.Name;
            tbl.Email = model.Email;
            tbl.Password = model.Password;
            db.tblUsers.Add(tbl);
            db.SaveChanges();

            return View();
        }

        public ActionResult ShowDataBaseForUser()
        {
            var item = db.tblUsers.ToList();
            return View(item);
        }

        public ActionResult Delete(int id)
        {
            var item = db.tblUsers.Where(x => x.ID == id).First();
            db.tblUsers.Remove(item);
            db.SaveChanges();
            var item2 = db.tblUsers.ToList();
            return View("ShowDataBaseForUser", item2);
        }

        
        public ActionResult Edit(int id)
        {
            if(id != 0)
            {
                var item = db.tblUsers.Where(x => x.ID == id).First();
                return View(item);
            }
            else
            {
                var item2 = db.tblUsers.ToList();
                return View("ShowDataBaseForUser", item2);
            }
           


        }

        [HttpPost]
        public ActionResult Edit(tblUser model)
        {
            var item = db.tblUsers.Where(x => x.ID == model.ID).First();
            item.Name = model.Name;
            item.Email = model.Email;
            item.Password = model.Password;
            db.SaveChanges();
            return View();
        }
    }
}

SipmleCRUD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "SetDataInDataBase", "Register", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Add Employee", "AddEmployeeInfo", "AddEemployee")</li>
                    <li>@Html.ActionLink("All Employee Details", "AllEmployeeDetails", "AddEemployee")</li>
                    <li>@Html.ActionLink("Show User Info", "ShowDataBaseForUser", "Register")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>